### ISSUE TITLE
[temp.arg.nontype] Consteval functions in default arguments in NTTP should be evaluated on call side.

### ISSUE THREAD

**Issue by tomaszkam** [cplusplus/CWG#156]
Full name of submitter (unless configured in github; will be published with the issue): Tomasz Kamiński

Reference (section label): [temp.arg.nontype]

Link to reflector thread (if any):

Issue description:

With a proposed resolution of CWG2631 the behavior of the functions like `std::source_location::current()` in the constructor parameter or class initializer may not consistent, between non-type template parameter and function parameter.  For example:
````
struct SourceLoc {
   std::size_t line = std::source_location::current().line;
   std::size_t column  = std::source_location::current().collumnt;
};

template<SourceLoc s1 = {}> // A
void foo(SourceLoc s2 = {}) {
  assert(s1.line == s2.line);
  assert(s1.line == s2.line);
}

foo(); // above assertions fails, as s1 refers to line A and s2 to this one
````

Note that with the use of NTTP it is possible to pass source information for invocation of function template specializations with a variadic number of parameters, as illustrated  here: https://godbolt.org/z/Tc6GMEefT

Suggested resolution:

Perform evaluation of `consteval` functions in default arguments for non-template parameters on call-site, as it is done for function parameters.

**Comment by jensmaurer** [comment]
Your suggestion would be a bigger can of worms.

Note that default template arguments are considered when instantiating a template, which happens only once even if you call a function template specialization multiple times.  In your example,

```
int main() {
  foo();
  foo();
  foo();
}
```

will call `foo` three times (and evaluate the function default argument three times), but it will instantiate the definition of `foo` only once (otherwise, we would get multiple definitions in the same translation unit).

So, any change in behavior here has deeper implications that are best explored in a paper to EWG.

**Comment by tomaszkam** [comment]
To clarify you mean that `foo` is currently instantiated once, but with the my suggestion could be instantiated up to tree times, depending on the value produced by default argument initializer?

That's indeed a very large and evolutionaly change, that may impact compilation times for existing program.
