### ISSUE TITLE
[intro.object] p11 The attribute clause requires an objective fact

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#263]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

> These operations select one of the implicitly-created objects **whose address is the address of the start of the region of storage**, and produce a pointer value that points to that object 

As discussed in https://github.com/cplusplus/draft/issues/5630, I have mentioned in the closed issue where I might not clearly express what the issue is. This issue is a logic problem. The intent of the rule is to say if the object is an implicitly created object and if suppose its addresses at the start of the region do not violate other rules and give the program a defined behavior, the object is a suitable created object. So, any implicitly created object satisfy these requirements can become a suitable created object. However, suppose which object has its address at the start of the region is subjective. Person A can consider the object of type `char`, B can consider the object of type `int`, and C can consider the object of type `Class`, as long as the consideration is reasonable. 

However, the rule says: one of the implicitly-created objects **whose address is the address of the start of the region of storage**, the object whose address is the address of the start of the region of storage is **an objective fact**. Either a certain object is or it is not, it cannot be changed by following different people's thought.

For example, I say A number whose value is `5` is greater than `0`. It's a common consensus, nobody will disagree. But, a suitable created object depends on what the person expects. 
````cpp
malloc(128); // #1
````
Person A says the suitable created object is `oa` of type `char`, can it be? it can. Person B says the suitable created object is `ob` of type `int`, can it be? it can. Person C says I want to use an object `oc` of type `Class`, hence the suitable created object for Person C is `oc`. Is anybody wrong? No, they are all right on their own perspective.

Now, these three people ask person D, who is right? From `D`'s perspective: 
1. `oa` is a suitable created object, so its address is the start of the region
2. `ob` is a suitable created object, so its address is the start of the region
3. `oc` is a suitable created object, so its address is the start of the region

According to [intro.object] p9, two irrelevant objects cannot have the same address, so must be only one is correct. **`D` just needs to find out the object whose address is the start of the region from an objective perspective** and then check which object in the list is the found object, then the person who says that object is right.

So, for the objective fact: one of the implicitly-created objects **whose address is the address of the start of the region of storage**, these three people cannot achieve a consensus, **because `D` cannot prove which object whose address is the start of the region from an objective perspective**, in his perspective, it's the paradox.  Skip out of any person's perspective, the attribute clause statements an objective fact. Hence, the intent conflicts with the wording.  

### Suggested resolution
Any object mentioned above is reasonable to become a suitable created object, but we cannot arbitrarily say the object whose address is the start of the region is the suitable created object. **This requires all people to achieve a consensus and to prove which object whose address is the start of the region, and they cannot because the intent is to build up parallel worlds and the selection will make the worlds be collapsed into a world**. So, defining the candidates of the suitable created object is more in line with the intention. Selecting which one from the candidates as the suitable created object depends on what the person wants the program to be.

**Comment by jensmaurer** [comment]
The wording in [intro.object] p10 recognizes that "If multiple such sets of objects would give the program defined behavior, it is unspecified which such set of objects is created."

"Unspecified" means this is a nondeterministic aspect of the abstract machine; see [intro.abstract] p3.

So, if your program consists exclusively of
```
int main() {
 malloc(128);
}
```
it is unspecified which set of implicitly created objects is actually created in the storage allocated by `malloc`. As a corollary, it is unspecified which object is the suitable created object.

I am not seeing a specific suggestion to modify the wording in your "suggested resolution" section, and I'm not seeing a defect in the specification here.

**Comment by xmh0511** [comment]
> I am not seeing a specific suggestion to modify the wording in your "suggested resolution" section, and I'm not seeing a defect in the specification here.

The defect is, if you say an object is a suitable created object or there exist multiple such sets of objects, you should first show their address is the start of the region, and you should cite the relevant formal rule to prove that. For example, assume you think the object of type `int` is the suitable created object, you should give the formal rules that specify the address of the object and say the address is the start of the region.  

As the suggested wording: 
> Any complete object and the subobjects thereof that would have the same address as that of the complete object form the set of candidates of the suitable created object. These operations select one from the set as the suitable created object and produce a pointer value that points to that object, if that value would result in the program having defined behavior.  If no such pointer value would give the program defined behavior, the behavior of the program is undefined. If multiple such pointer values would give the program defined behavior, it is unspecified which such pointer value is produced.

**Comment by frederick-vs-ja** [comment]
> Now, these three people ask person D, who is right? From `D`'s perspective:
> 
> 1. `oa` is a suitable created object, so its address is the start of the region
> 2. `ob` is a suitable created object, so its address is the start of the region
> 3. `oc` is a suitable created object, so its address is the start of the region
> 
> According to [intro.object] p9, two irrelevant objects cannot have the same address, so must be only one is correct.

You seemingly misread the current wording. The three interpretations (or possibly more precisely, three different sets of valid interpretations of the set of implicitly created objects) can't simultaneously hold, but this is not an issue. Because the wording means that if there's one valid interpretation to make these operations well-defined, then the operations are just well-defined. There's no requirement involving two different interpretations.

> **This requires all people to achieve a consensus and to prove which object whose address is the start of the region, and they cannot because the intent is to build up parallel worlds and the selection will make the worlds be collapsed into a world**.

I don't think this is happening.

> > Any complete object and the subobjects thereof that would have the same address as that of the complete object form the set of candidates of the suitable created object. [...]

This is wrong to me. As this seems implying that given one object `X` in the set of candidates, there may be another object `Y` which is created in the region and located at some address lower than that of `X`.

**Comment by xmh0511** [comment]
> This is wrong to me. As this seems implying that given one object X in the set of candidates, there may be another object Y which is created in the region and located at some address lower than that of X.

"the candidates of the suitable created object" does not depend on whose address is the start of the region, it just gives reasonable candidates, you can select anyone from the set.  

Again, assume you think the object of type `int` is the suitable created object, you should give the formal rules that specify the value of the address of the object and that say the address is the start of the region, or we can judge the specified value of the address(i.e. said by the rule if any) is the start of the region by comparing. 

Where are these rules?

**Comment by frederick-vs-ja** [comment]
> I don't know how you associate the candidates with other irrelevant objects from the aspect of address.

I meant that the sets you suggested can contain unreasonable candidates. The wording seemingly allowed seeking to a lower address via the address of a suitable created object and access the object at that address.

> The set didn't talk about address at all.

This is problematic. Without talking about address, it doesn't seem possible to make seeking to a lower address undefined.

> Again, assume you think the object of type `int` is the suitable created object, you should give the formal rules that specify the value of the address of the object and that say the address is the start of the region, or we can judge the specified value of the address(i.e. said by the rule if any) is the start of the region by comparing.

Again, I don't think generally we can start to say _the_ object without specifying the value of its address.

**Comment by xmh0511** [comment]
> I meant that the sets you suggested can contain unreasonable candidates. 

Could you please give a counter-example? 

> Again, I don't think generally we can start to say the object without specifying the value of its address.

So, you agree we should first know the value of the address of an object, then compare the value with the value of the address of the start of the region to check whether the object is a suitable created object. Then, we fall into the problem: where are these rules specify the value of the address of any implicitly created objects we want to check?

**Comment by frederick-vs-ja** [comment]
> Could you please give a counter-example?

Assuming allocation successes.
```C++
auto ptr = static_cast<char*>(malloc(42));
*reinterpret_cast<char*>(reinterpret_cast<uintptr_t>(ptr) - 8) = '*';
```

Although there're some implementation-defined aspects of such seeking, the candidate set you suggested would make the interpretation that "`char` objects `X` and `Y` are created at offset 0 and 8 respectively, and `Y` is the suitable created object pointed-to by `ptr`" valid for some (all mainstream?) implementations and indicate that the write has no UB.

> Generally speaking, we do not require to know the exact value of the address of an object:
> 
> ```c++
> void fun(){
>    int a = 0; // what is the exact value of the address of the object? we don't need to know
> }
> ```

In this case, the object is explicitly created, so we can identify the object via some other ways. However, for some implicitly created object which we want to refer as "the object", we have to specify in which structure relative to the region, which generally implies whether it's address is same as the start of the region.

The term "address" in the standard doesn't need to map to physical or virtual address. For example, we can still say address of some object during constant evaluation, but the numeric value of address in the usual meaning doesn't make sense (any attempt to retrive it makes the constant evalutation failed).

In other words, we probably have to treat the address of a complete object in constant evaluation as a standalone thing, and only think the address of each of its subobject to be only "the structure with respect to the complete object".

> So, the point is, it is not possible to specify the value of the address for every object, so we cannot define which object is a suitable created object by comparing whether its address equals the address of the start of the region. We should define a set of viable candidates for the suitable created object, which is an abstract concept.

Now, even though implicitly created object can only be touched outside of constant evaluation, I think we can still treate the address of a dynamically allocated storage, a defined complete object, or something like as a standalone thing (such storages and storages occupied by the complete objects are collectively called _storage instances_ in [WG14 N3005](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3005.pdf)).

And then, I'd say specifying the address of that implicitly-created object in a dynamically allocated storage can only means specifying the structure with respect to the region, although some offsets needs to be additionally specified, because we sometimes need to specify complete objects at non-zero offset (relative to the start of the whole storage or the array providing storage).

**Comment by xmh0511** [comment]
> Although there're some implementation-defined aspects of such seeking, the candidate set you suggested would make the interpretation that "char objects X and Y are created at offset 0 and 8 respectively, and Y is the suitable created object pointed-to by ptr" valid for some (all mainstream?) implementations and indicate that the write has no UB.

You seem to misunderstand the proposed wording. Once you select one object from the set as the suitable created object, it will have the address at the start of the region.  The original wording says the object is a suitable created object because its address is the start of the region, this wording cannot be determined because no rule specifies the address for comparing. In my wording, we give a set of candidates for the suitable created object, once we select one from the set as the suitable created object, the object's address is the start of the region. 
````cpp
auto ptr = static_cast<char*>(malloc(42));
````
That means the set of candidates could be `{ char, char[42], ... }`, and which one is selected depends on what you want your program to be. So `reinterpret_cast<uintptr_t>(ptr) - 8` is UB as per [expr.add] p4. I said the definition of which object is a suitable created object does not depend on the address does not mean we didn't give the selected suitable created object an address.

**Comment by xmh0511** [comment]
> I don't think the intent can be achieved without explicitly mentioning some address. Perhaps you should additionally say that the address at the start of the region is determined via the address of that object.

So, the supplement proposed wording may be: 
> Further, after implicitly creating objects within a specified region of storage, any complete object and the subobjects thereof that would have the same address as that of the complete object form the set of candidates of the suitable created object. These operations select one from the set as the suitable created object and produce a pointer value that points to that object if that value would result in the program having defined behavior. **The address of the selected suitable created object is the address of the start of the region of storage**. If no such pointer value would give the program defined behavior, the behavior of the program is undefined. If multiple such pointer values would give the program defined behavior, it is unspecified which such pointer value is produced.

**Comment by jensmaurer** [comment]
I believe you can argue about abstract properties of an object such as its "address", which is essentially the integer number you get via `interpret_cast<std::uintptr_t>(&object)`, without actually saying what its specific value is. There are other rules throughout the standard (e.g. pointer-interconvertibility and distinct complete objects occupy distinct storage and thus have different addresses) that feed into the "same address" equivalence relation that we need to query.

Analogously, I know there are infinitely many prime numbers, but I can't name a specific one larger than 10^(10^8).

Furthermore, I'd like to point out that "implicitly created objects" come in sets for each of the possibilities. (For example, we could have two complete objects of type `char` or a single array of char in storage of size 2.)  We first select one set among the sets, and then, within a given set, we choose the object allocated at the lowest address in that set. off-topic: For the latter choice, I think we can restrict ourselves to complete objects, because we could simply choose a different set in the first step instead of choosing a subobject in the second step (pointer interconvertibility allows looking at a subobject regardless). 

I also noticed that some of the wording changes proposed so far appear to hint that the address returned by malloc (etc.) is somehow derived from the suitable created object. That is not the case. We first allocate storage, the beginning of that storage has an address, and then do we fit implicitly created objects into that storage.  I believe the status quo "whose" wording exactly conveys that notion.

In this lengthy discussion, I have not seen a wording suggestion that I would actually consider an improvement.

**Comment by frederick-vs-ja** [comment]
> For the latter choice, I think we can restrict ourselves to complete objects, because we could simply choose a different set in the first step instead of choosing a subobject in the second step (pointer interconvertibility allows looking at a subobject regardless).

I guess we should not. The status quo covers cases where a non-pointer-interconvertible subobject has the same addess as its complete object. E.g. I believe it's indended that an array element subobject can be a suitable created object, and it would make such cases uncovered to rely on pointer-interconvertibility.

(Although the equality of addresses of an array and its first element might be not specified well enough...)

**Comment by jensmaurer** [comment]
(I'm wondering how you would validly convert from the pointer-to-element to a pointer that "sees" the entire array. Anyway, we seem to agree that the current wording does what it should.)

**Comment by xmh0511** [comment]
> Analogously, I know there are infinitely many prime numbers, but I can't name a specific one larger than 10^(10^8).

Anyway, we can give a reasonable range. 

> we choose the object allocated at the lowest address in that set

I have to say there is no rule specifying which object is allocated at the lowest address.
