### ISSUE TITLE
CWG2102 [expr.new] Clarify if the constructor needs to be accessible for a class type when using new T[0]

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#320]
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [expr.new]

Link to reflector thread (if any): https://stackoverflow.com/questions/76307898/new-a0-initialization-of-zero-size-array-with-dynamic-storage-duration-for-a

**Issue description:**

It is not clear if the following program is well-formed or ill-formed according to the current wording. 

```
class A {
    A()=delete;    
};

int main()
{
     auto ptr = new A[0];  
}
```
We see [implementation divergence](https://godbolt.org/z/qKKrjj8sn) here. As per [expr.new]:

> When the value of the expression is zero, the allocation function is called to allocate an array with no elements.

One possible interpretation of the above clause is that since the array doesn't have any elements, there is no need for any initialization and hence no need for the constructor to be accessible or to exist at all. This should be clarified. The intention seems that there is no need for the ctor to exist or be accessible.

**Suggested resolution:**

It should be clarified that whether the above behaves as if there is no initialization and so no need for accessible ctor etc or the constructor needs to be accessible.

**Comment by ranaanoop** [comment]
@languagelawyer Good point, so it seems the easiest(simplest) is to add that even if the `expression` comes to be `0`, the ctor still needs to be accessible.

**Comment by languagelawyer** [comment]
As it was noticed on SO, CWG2102?

**Comment by frederick-vs-ja** [comment]
Ah, CWG2102 seems to be resolved editorially ([EDIT2608](https://wg21.link/edit2608)). @jensmaurer

**Comment by jensmaurer** [comment]
Right, that editorial issue helps CWG2102 a bit, but not all questions asked in CWG2102 are addressed by that editorial fix.

**Comment by jensmaurer** [comment]
I've amended CWG2102 with the question about `T[0]`, and I've added a proposed resolution there.

**Comment by frederick-vs-ja** [comment]
The currently proposed resolution hasn't address `new A[0]()` or `new A[0]{}`.

And there is also implementation divergence now ([Godbolt link](https://godbolt.org/z/WTrG4ooEz)):
|  | `new A[0]` | `new A[0]()` | `new A[0]{}` |
|--|--|--|--|
| GCC | √ | √ | √ |
| Clang | × | × | √ |
| MSVC | × | × | × |

**Comment by jensmaurer** [comment]
Fixed: CWG2102

**Comment by RealLitb** [comment]
How is this different from w.r.t. checking of access?

   for(int i = 0; i < 0; i++) new Class;

The '0' in your new-expression is not even in a place that is constrained syntactically to a constant-expression (it's a new-type-id.. and if your were to parenthesize it, it would be ill-formed with `0` because it would become a declarator), making it match my for-loop really nicely. Access-checking is done independently of whether an object actually is created at runtime - it suffices if it appears in the CFG, I think. Think about

   void f(X = X()); // access check happens here, even if `f` is not called.

**Comment by RealLitb** [comment]
We have the rule:

>Access control is applied uniformly to declarations and expressions[.](https://eel.is/c++draft/class.access#general-4.sentence-1)

That means, access control does not apply to evaluations of expressions, but to expressions (statically). A note may be sufficient somewhere in expr.new:

> [Note: Access checking on the (implicit) call-expression to constructors, destructors and allocation functions will happen regardless of whether these are actually evaluated, even in the case of creation or destruction of an array without elements. -- end Note]

**Comment by jensmaurer** [comment]
@reallitb, is your comment in any way directed at the current proposed resolution of CWG2102, or just at the discussion in this ticket?

**Comment by RealLitb** [comment]
> @RealLitb, is your comment in any way directed at the current proposed resolution of [CWG2102](https://cplusplus.github.io/CWG/issues/2102.html), or just at the discussion in this ticket?

It was primarily directed to this discussion. Because access checks happen on expressions, and expressions are part of the program and initializations as well as function calls (including those for excess array elements) are part of full-expressions, in my reading access checking in this case is already normatively specified. Whether or not at runtime those initializer-expressions  (default-initialization for example) are evaluated does not and cannot influence access checking. But I agree it's not as clear as I initially thought, regarding the difference between constant and non-constant array sizes!

I don't know whether most would expect there to be a difference w.r.t. to the access-checking between 

    new HasNoDefaultCtor[1]{somearg};

and

    new HasNoDefaultCtor[0];

though! There's explicit wording in CWG2102 for the first case for constant array sizes to not access-check a "hypothetical initialization". But the second case doesn't differentiate between them at all. The compiler has it all on the table that there's no initialization ever. But, I guess, this behavior was approved by the CWG, so there we go. 

It should be noted that if we today still had the `initializer_list<HasNoDefaultCtor>{}` expression use the usual backing-array semantics, instead of value-initializing the initializer_list, it would render "{}" on initializer_list illegal, since it would necessiate a default-constructed zero-size array (see #982 - now irrelevant because an empty brace pair value-initializes the initializer_list instead).

**Comment by frederick-vs-ja** [comment]
> It should be noted that if we today still had the `initializer_list<HasNoDefaultCtor>{}` expression use the usual backing-array semantics, instead of value-initializing the initializer_list, it would render "{}" on initializer_list illegal, since it would necessiate a default-constructed zero-size array (see #982 - now irrelevant because an empty brace pair value-initializes the initializer_list instead).

This should be another issue as the backing array is always statically sized. It seems to me that we should just avoid the backing array when the list is empty. See #413.
