### ISSUE TITLE
[intro.races] p13 `shall` vs. `is`

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#373]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[intro.races] p13 says:
> The value of a non-atomic scalar object or bit-field M, as determined by evaluation B, **shall be** the value stored by the visible side effect A.

The note says
>[Note 12: If there is ambiguity about which side effect to a non-atomic object or bit-field is visible, then the behavior is either unspecified or undefined. — end note]

`shall` means if the rule is violated, the implementations shall diagnose per [intro.compliance.general] p2, which means the program is **ill-formed**. Both unspecified and undefined behavior does not violate the rule. Consider the case where there would be no visible side effect to the value computation `B`, which would happen to cause the program data race per [intro.races] p21, which is defined as `UB`, however, this situation has first violated the `shall`, which means the implementation should first issue one diagnostic message, which means we never fall into UB.

### Suggested Resolution
we may want to say
> The value of a non-atomic scalar object or bit-field M, as determined by evaluation B, is the value stored by the visible side effect A.

**Comment by frederick-vs-ja** [comment]
I think other occurences in [intro.races] are also problematic. Perhaps we can resolves this editorially.

**Comment by jensmaurer** [comment]
Please file an editorial pull request for these, preferably fixing all "shall"s.

**Comment by jensmaurer** [comment]
The problem we have for the C++ standard is that it defines requirements on two levels: Requirements on the implementation, and requirements on (well-formed) programs. This is a rather unique situation for programming languages, which is not well-reflected in the (rather general) ISO Directives.

We admit as much in [intro.compliance.general] p2:

> Although this document states only requirements on C++ implementations, those requirements are often easier to understand if they are phrased as requirements on programs, parts of programs, or execution of programs.

Our operation mode for the past decade (at least) has been to clarify requirements on implementations by saying "an implementation shall ..." where the emphasis is desirable, and otherwise just describe the behavior of C++ using "is" etc. For example, [expr.add] p3 says "The result of the binary + operator is the sum of the operands." even though it is a requirement on the implementation that the + operator "shall" yield a certain result.

We use "shall" to describe diagnosable rules for programs. For example, [expr.add] p1 says

> For addition, either both operands shall have arithmetic type, or one operand shall be a pointer to a completely-defined object type and the other shall have integral type.

If we can't use "shall" for that purpose, we'd have to use "the program is ill-formed if ..." phrasings everywhere, which (depending on context) might just be longer and more verbose or actually awkward to phrase and harder to understand.

Obviously, the rules for atomic operations behavior are requirements on the implementation (not diagnosable rules for programs), so "shall" is undesirable per the above.

**Comment by languagelawyer** [comment]
> We admit as much in [intro.compliance.general] p2:
> 
> > Although this document states only requirements on C++ implementations, those requirements are often easier to understand if they are phrased as requirements on programs, parts of programs, or execution of programs.

I know. Often, not always. 
> The value of a non-atomic scalar object or bit-field M, as determined by evaluation B, shall be the value stored by the visible side effect A.

clearly reads as the requirement put directly on an implementation. So shall here is perfectly fine. Even required, according to the ISO rules.

> We use "shall" to describe diagnosable rules for programs.

diagnosable ≠ shall be diagnosed, since a program ≠ an execution of a program. http://eel.is/c++draft/intro.compliance.general#2.3 speaks about the former, not the later.

**Comment by jensmaurer** [comment]
> since a program ≠ an execution of a program

Exactly, and that's why we shy away from "shall" for runtime behavior (there's no way to give a diagnostic on the violation of runtime things, and we have had confusion in that area in the past).

**Comment by languagelawyer** [comment]
> and that's why we shy away from "shall" for runtime behavior (there's no way to give a diagnostic on the violation of runtime things

There is no requirement to diagnose "shall" violation, which is not "contained" in a program, but "happened'" during program execution. Per http://eel.is/c++draft/intro.compliance.general#2.3, diagnostics is required only for "contained" violations.

But I can see the problem, yes. There is nothing in http://eel.is/c++draft/intro.compliance.general#2 saying what an implementation shall do when semantic rule is violated at runtime.

P.S. Just in case. "shall for runtime behavior" is "shall" used when the standard describes requirement for an implementation in terms of requirements on a(n execution of a) program. I don't know good examples, I'll link https://timsong-cpp.github.io/cppwp/n4868/dcl.ref#5.sentence-3 (CWG453). The paragraph which is the subject of this non-issue is not an example of "shall for runtime behavior", the "shall" here is used to describe the requirements for an implementation _directly_.

**Comment by languagelawyer** [comment]
> [CWG453](https://cplusplus.github.io/CWG/issues/453.html) is exactly a case where "shall" is used and it looks like a compile-time-diagnosable situation

IDK why necessary as "a compile-time-diagnosable situation"

We have
> Although this document states only requirements on C++ implementations, those requirements are often easier to understand if they are phrased as requirements on programs, parts of programs, or **execution of programs**

so this could be read as requirement on an implementation executing the program. Except that what we want to say is that there is no requirement. And this is because the use "shall" there is wrong. Not because someone may thing that "diagnostics" is involved every time they see "shall" (without NDR).

But after all, I think we agree that "shall" in CWG453 is bad and here is good. Better and more correct than "is".

**Comment by languagelawyer** [comment]
> Clarifying how and when we use "shall"

If you use it as specified in ISO/IEC Directives, Part 2, no need, since it is referenced in the Foreword.

If you gonna use it incompatibly with ISO/IEC Directives, Part 2, then
> This document was drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2 (see www.iso.org/directives).

will need to be removed from Foreword. (But I suspect then ISO won't approve "This document" as an ISO standard?)

**Comment by languagelawyer** [comment]
@RealLitb note I'm not saying that the use of "shall" in CWG453 is a good thing, it would be extremely hard to reformulate it as a positive requirement on an implementation [when executing a program]. So, instead, the lack of requirement should be indicated.

As noted by @jensmaurer , "The result of the binary + operator <del>is</del> <ins>shall</ins> be the sum of the operands." would be perfectly fine, since it specifies a positive requirement.

**Comment by languagelawyer** [comment]
> Feel free to write a paper suggesting an alternative with specific examples, submit it to WG21, and be prepared to join a meeting to discuss your paper.

I think someone who will want to remove «This document was drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2» from the Foreword will need to prepare a paper.

I do not want.

**Comment by frederick-vs-ja** [comment]
> I think someone who will want to remove «This document was drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2» from the Foreword will need to prepare a paper.

I don't think anybody wants to do this. In any case, the intent is just clarifying how and when we impose requirements _without_ "shall". The remain uses of "shall" should still be "drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2".

**Comment by languagelawyer** [comment]
> how and when we impose requirements without "shall"

Please read again what I've cited above:
> The verbal forms shown in Table 3 shall be used to express requirements.
> Table 3: Preferred verbal form: «shall»/«shall not»

I think even when expressing requirements on an implementation using other forms of spelling (as requirements on programs, executions of programs, etc.), "shall" still shall be used, so that reader could distinguish requirements from non-requirements.

**Comment by frederick-vs-ja** [comment]
> > The verbal forms shown in Table 3 shall be used to express requirements.
> > Table 3: Preferred verbal form: «shall»/«shall not»
> 
> I think even when expressing requirements on an implementation using other forms of spelling (as requirements on programs, executions of programs, etc.), "shall" still shall be used, so that reader could distinguish requirements from non-requirements.

I think the cited content means that when «shall»/«shall not» are used, they shall be used to express requirements, but not the other way around - it doesn't mean that when requirements are expressed, «shall»/«shall not» shall be used.

**Comment by languagelawyer** [comment]
> [intro.races] p13 says:
> 
> > The value of a non-atomic scalar object or bit-field M, as determined by evaluation B, **shall be** the value stored by the visible side effect A.
> 
> `shall` means if the rule is violated, the implementations shall diagnose

I think woulda be funny to see attempts to write a program which "violates" [intro.races]/13. Shoulda asked for this before disclosing it is impossible by the nature of the paragraph.

**Comment by languagelawyer** [comment]
@frederick-vs-ja a more complete citation:
> The user of the document shall be able to identify the requirements he/she is obliged to satisfy in order to claim conformance to a document. The user shall also be able to distinguish these requirements from other types of provision (recommendations, permissions, possibilities and capabilities).
>
> It is essential to follow rules for the use of verbal forms so that a clear distinction can be made between requirements, recommendations, permissions, possibilities and capabilities. To avoid risk of misinterpretation, verbal forms that are not defined in Table 3 to Table 7 shall not be used for the expression of provisions.

So it is in both directions. (BTW, I don't understand how did you manage to read as you did; I may understand it is kinda possible to do it the other way around)

(Waiting for someone to claim that
> verbal forms that are not defined in Table 3 to Table 7 shall not be used for the expression of provisions

does not prohibit the use of **non-verbal** forms to express requirements)

**Comment by frederick-vs-ja** [comment]
> So it is in both directions. (BTW, I don't understand how did you manage to read as you did; I may understand it is kinda possible to do it the other way around)

One reason is that [ISO/IEC Directives, Part 2](https://www.iso.org/sites/directives/current/part2/index.xhtml) itself sometimes expresses requirements without "shall". E.g., in the following paragraph:
> 24.3 Numbering and subdivision
> Within a given clause or subclause, notes shall be numbered sequentially. The numbering restarts at each new subdivision. A single note in a subdivision shall not be numbered.

the plain "restarts" also expresses a requirement.

**Comment by languagelawyer** [comment]
> One reason is that [ISO/IEC Directives, Part 2](https://www.iso.org/sites/directives/current/part2/index.xhtml) itself sometimes expresses requirements without "shall".

1. ISO/IEC Directives, Part 2 might not be drafted according to ISO/IEC Directives, Part 2 (unlikely)
2. This can be an issue (likely)

So, you are gonna to use one unintentional mistake as an excuse to do many intentional?

**Comment by jensmaurer** [comment]
> ISO/IEC Directives, Part 2 might not be drafted according to ISO/IEC Directives, Part 2

This is exactly the case. See the foreword, page ix:

> It is not the intention that the ISO/IEC Directives, Part 2 follow the same structure and drafting rules as International Standards and associated publications (referred to collectively as “documents”, see 3.1.1).
