### ISSUE TITLE
[basic.fundamental] p2 `modulo` is ambigous in defining result

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#606]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[basic.fundamental] p2 says:
> arithmetic for the unsigned type is performed modulo 2<sup>N</sup>.

Consider this example:
````cpp
int main(){
   auto r = 2u - 4u;
}
````
[Modulo Wiki](https://en.wikipedia.org/wiki/Modulo) says
![图片](https://github.com/user-attachments/assets/34bbce39-1897-436e-b7cf-44260e56df6c)

The rule defines the result as `-2 mod 4294967296`, which in turn, is determined by what `modulo` means here. `modulo` has different definitions on mathematics and computer science, which determines whether the remainder is a positive number or a negative.  

### Suggested Resolution

> arithmetic for the unsigned type is a unique value of that type that is congruent to the result of the arithmetic modulo 2<sup>N</sup>

**Comment by frederick-vs-ja** [comment]
Per search results of "is performed modulo", I find that when one says "is performed modulo" (exactly these 3 English words), the operation is always arithmetic modulo and there doesn't seem any counterexample. Also, I guess the sentence should be moved somewhere in [expr] as it's entirely about evaluation of some expressions.

Concerns here can be handled editorially IMO (if improvements are desired).

> arithmetic for the unsigned type is a unique value of that type that is congruent to the result of the arithmetic modulo 2<sup>N</sup>

The suggestion seemingly says that "some kind of arithmetic is some value", which seems semantically ill-formed to me. Presumably "produces" should be used instead of "is".

**Comment by Eisenwave** [comment]
Modulo is only ambiguous when the operands are potentially negative.

In the context of `unsigned` numbers, all math is done with positive numbers (and positive divisor), and all definitions of "modulo" or "modular arithmetic" yield the same result.

This is definitely editorial; I honestly don't find the current wording all that confusing though.

**Comment by jensmaurer** [comment]
Since negative values can't be represented in unsigned integers (and the divisor is always positive, obviously), I'm not seeing much leeway for misunderstanding.  Oh, and the incoming text does say "arithmetic ... is performed modulo 2^N", so there's your "arithmetic" already.
