### ISSUE TITLE
Do substitution failures in an attribute-specifier-seq of a function declaration occur in the immediate context?

### ISSUE THREAD

**Issue by tahonermann** [cplusplus/CWG#624]
**Full name of submitter (unless configured in github; will be published with the issue):** Tom Honermann

**Reference (section label):** [[temp.deduct.general]](https://eel.is/c++draft/temp.deduct.general)

**Link to reflector thread (if any):** N/A

**Issue description:**

It is unclear whether an *attribute-specifier-seq* that appears in a function declaration is in the immediate context and therefore contributes to overload resolution. Assuming that `attr` is a recognized name of an attribute that takes a single type argument, is the following program well-formed and, if so, what is its behavior?
```
template<typename T>
[[attr(typename T::invalid)]]
void ft(int);  // #1
template<typename T>
void ft(long); // #2
void f() {
  ft<int>(0);
}
```

I see three possibilities:
- Attributes are not in the immediate context, overload resolution selects #&NoBreak;1, the program is ill-formed because substitution results in an invalid type for the attribute argument.
- Attributes are in the immediate context, overload resolution discards #&NoBreak;2 as a candidate and selects #&NoBreak;2, the program is well-formed.
- It is implementation-defined whether any particular attribute is in the immediate context.

Relevant CWG issues: [CWG 1844](https://wg21.link/cwg1844) and [CWG 2296](https://wg21.link/cwg2296).

**Suggested resolution:**

**Comment by t3nsor** [comment]
The *attribute-specifier-seq* in your example is not part of the deduction substitution loci. https://eel.is/c++draft/temp.deduct.general#7

If the question were to arise with a standard attribute (and I don't think it does right now, because the only standard attribute that takes arguments is `assume`, which cannot be in that position) we would definitely have to answer it, because if it's left out of the deduction substitution loci, then we must state the point at which its instantiation occurs (most likely, when the instantiated function is selected by overload resolution).

For a non-standard attribute, I'd think that https://eel.is/c++draft/dcl.attr.grammar#6 already gives enough latitude for the implementation to do whatever it wants.

**Comment by jensmaurer** [comment]
Nothing to see, I'd say.

**Comment by tahonermann** [comment]
Implementation-defined it is. Thanks for the link to dcl.attr.grammar, @t3nsor; I agree that suffices.

**Comment by tahonermann** [comment]
[P3423R0 (Extending User-Generated Diagnostic Messages)](https://wg21.link/p3423r0) will require answering this question since it proposes extensions to the `[[deprecated]]` and `[[nodiscard]]` attributes that would allow for substitution failures to occur in the attribute argument. Section 4.5, "What If The Message Parameter Is Invalid?" touches on similar concerns, but doesn't address substitution failure.

**Comment by jensmaurer** [comment]
We'll climb that hill when we get there.

**Comment by tahonermann** [comment]
> We'll climb that hill when we get there.

It seems we just got there with the EDG approval of [P3423R1](https://wg21.link/p3423r1) in Kona ([EWG minutes](https://wiki.edg.com/bin/view/Wg21kona2025/EWGP3423Notes)).

**Comment by villevoutilainen** [comment]
I appreciate the subtle suggestion that EDG should have design decision powers over EWG; I think that idea has some very attractive merits.
