### ISSUE TITLE
CWG2606 [expr.static.cast] static_cast from void* doesn't handle similar types

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/CWG#75]
Full name of submitter (unless configured in github; will be published with the issue): 

Reference (section label): [expr.static.cast]/13

Link to reflector thread (if any):

Issue description:

```
struct S {
  int a[5];
} s;
int (*p)[] = reinterpret_cast<int(*)[]>(&s);
int n = (*p)[0];
```

I think this should have defined behavior: a pointer to `s` and a pointer to `s.a` are pointer-interconvertible, so you should be able to navigate between them this way. But I think it doesn't work, because the type of the pointer-interconvertible object is `int[5]`, not `int[]`.

Suggested resolution:

Change in [expr.static.cast]/13:

> [...] Otherwise, if the original pointer value points to an object `a`, and there is an object `b` of type <ins>similar to</ins> `T` <del>(ignoring cv-qualification)</del> that is pointer-interconvertible with `a`, the result is a pointer to `b`. Otherwise, the pointer value is unchanged by the conversion.

**Comment by languagelawyer** [comment]
The intent is «Otherwise, the result is the value/result of the (converted) operand»

**Comment by jensmaurer** [comment]
@tahonermann , the more subtle implication is that while you changed the static type of the pointer in the expression, the pointer still points to the original object.

For example, `int i; long * q = reinterpret_cast<long *>(&i);`
In that case,"q" still points to an "int", although its type is "pointer to long". Which is likely not doing any good in the long run.

**Comment by jensmaurer** [comment]
CWG2606

**Comment by languagelawyer** [comment]
Evolutionary? 🌚

**Comment by jensmaurer** [comment]
I don't think so. This is a minor consistency fix that turns undefined behavior into well-defined behavior for a certain corner case.

**Comment by xmh0511** [comment]
It seems that CWG2606 also as a drive-by that fixes https://github.com/cplusplus/draft/issues/5356. 
````cpp
int const v = 0;
void const* cvptr = &v;
void* vptr =  const_cast<void*>(cvptr);
int* iptr = static_cast<int*>(vptr );  // #3
````

The destination type of the conversion at `#3` is "pointer to int". Then we say an object `b` similar to `int` implies that `b` can be of type `int`, `const int`, `volatile int`, or `volatile const int`. Since `vptr` originally points to an object `v` of type `int const`, only if `b` has type `int const` will [basic.compound] p4(especially, bullet 4.1) applies here.   
> Two objects a and b are pointer-interconvertible if:
>> - **they are the same object**, or

Since `a` and `b` are of the same type, which can be considered as the same object.
