### ISSUE TITLE
CWG2545 [dcl.attr.nouniqueaddr] Is `[[no_unique_address]]` entirely ignorable by the implementation?

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/CWG#9]
Full name of submitter (unless configured in github; will be published with the issue): Jiang An

Reference (section label): [dcl.attr.nouniqueaddr]

Link to reflector thread (if any):

Issue description:

This issue is raised from the discussion in #8.

There is a design guideline of standard attributes, mentioned in an early proposal of `[[no_unique_address]]` ([P0840R0](https://wg21.link/p0840r0)):

> compiling a valid program with all instances of a particular attribute ignored must result in a correct interpretation of the original program

However, it seems that `[[no_unique_address]]` does not follow this guideline. As `[[no_unique_address]]` makes a member subobject potentially-overlapping, ignoring it makes the implementation consider such a subobject non-potentially-overlapping, which may change the behavior of a well-defined program in two ways.

First, according to [intro.object]/8, non-potentially-overlapping subobjects are never considered to have zero size. And ccording to [meta.unary.prop], whether a member subobject has zero size affects the result of `is_empty`.

As a result, ignoring `[[no_unique_address]]` may change the behavior of a program dependent on `std::is_empty_v<T>` or make it ill-formed, if `T` has a non-static data member that previously has zero size.

Second, according to [expr.const]/(15.8), any core language undefined behavior is required to be diagnosed in constant evaluation, and results in constant evaluation failure. However, whether the particular constant evaluation fails can be sometimes made observable by SFINAE techniques, without actually triggering UB.

Consider the following function (given `Cond` being `true`):
```C++
template<bool Cond>
constexpr bool test_potentially_overlapping()
{
    struct Foo {
        Foo() = default;
    };
    struct Bar {
        [[no_unique_address]] Foo f;
    };
    
    if constexpr (Cond)
    {
        Bar b{};
        std::construct_at(&b.f); // storage reuse
        b.~Bar(); // !!!
        std::construct_at(&b);
    }
    
    return true;
}
```
When `b.f` is potentially-overlapping, it's not transparently replaceable by the newly constructed `Foo` object ([basic.life]/(8.4)), so we may say that the newly constructed `Foo` object is not nested within `b`. And thus the lifetime of `b` is ended by the construction of new `Foo` object ([basic.life]/(1.5)), and then calling destructor for `b` has undefined behavior ([class.dtor]/19).

This function can be wrapped by some SFINAE techniques, and then gives a constant expression which is `true` if and only the compiler consider the destructor call is well-defined, which also reflects whether `[[no_unique_address]]` is ignored.

Although the implementation can say it has a `[[no_unique_address]]`-ignoring mode (like MSVC) that a potentially-overlapping member subobject has non-zero size, the standard currently doesn't say that the potentially-overlapping property, which affects constant evaluation and SFINAE, is ignorable. As a result, the implementation is still unconditionally required to consider `[[no_unique_address]]` during constant evaluation.

Note that currently compilers (gcc 12/clang 11+/icc 2021.5.0) don't diagnose this UB even if `[[no_unique_address]]` is affective (Compiler Explorer link: https://gcc.godbolt.org/z/MW6xjdhYq).

Suggested resolution:

Change [dcl.attr.nouniqueaddr]/1 as indicated:
> The _attribute-token_ `no_­unique_­address` specifies that a non-static data member is a potentially-overlapping subobject ([intro.object]) **if the implementation recognizes this attribute**. **It is implementation-defined whether `no_­unique_­address` is recognized.** ...

Change [intro.object]/(7.2) as indicated:
> **if the implementation recognizes the `no_­unique_­address` attribute,** a non-static data member declared with ~the `no_­unique_­address`~ **this** attribute.

**Comment by jensmaurer** [comment]
I agree with the SFINAE train of thought considering the mechanics of the feature, although we tend to ignore changes in SFINAE behavior as "part of the intended effects".

As for the is_empty situation, I guess we're discussing this example:
```
struct A { };
struct B {
  [[no_unique_address] A a;
};
static_assert(std::is_empty_v<B>);
```

**Comment by frederick-vs-ja** [comment]
> As for the is_empty situation, I guess we're discussing this example:
> 
> ```C++
> struct A { };
> struct B {
>   [[no_unique_address]] A a;
> };
> static_assert(std::is_empty_v<B>);
> ```

Yes. And despite of `static_assert`, the result (or the size of some affected type) may be used in `if constexpr` or elsewhere, which doesn't affect the well-formedness but change the behavior of the program.

**Comment by frederick-vs-ja** [comment]
@jensmaurer 
Sorry for bothering many times. Now I think the clearest solution is explicitly stating that `no_unique_address` can be entirely ignored, and if ignored, it never makes a member subobject potentially-overlapping.
(And hence we can just use the potentially-overlapping property to specify empty classes.)

----
Suggested resolution:

Change [dcl.attr.nouniqueaddr]/1 as indicated:
> The _attribute-token_ `no_­unique_­address` specifies that a non-static data member is a potentially-overlapping subobject ([intro.object]) **if the implementation recognizes this attribute**. **It is implementation-defined whether `no_­unique_­address specifies` is recognized.** ...

Change [intro.object]/(7.2) as indicated:
> **if the implementation recognizes the `no_­unique_­address` attribute,** a non-static data member declared with ~the `no_­unique_­address`~ **this** attribute.

**Comment by jensmaurer** [comment]
I think that relying on the effects of `no_unique_address` in your program in any way is just a badly-written program, because even with `no_unique_address` present, you might still get `std::is_empty == false` (if you happen to be on an implementation that doesn't honor `no_unique_address` in that particular situation, or in general.

I think the wording was carefully crafted that `no_unique_address` can be ignored in some places and not in others; `no_unique_address` just reduces the guarantees that you get for your program. (If you ask for / rely on any of those properties whose result is effectively unspecified with `no_unique_address` present, that's just a bug in your program.)

Note that an implementation might honor `no_unique_address` in some situations and not in others. See  intro.object p8: "Otherwise, the circumstances under which the object has zero size are implementation-defined." This is more or less what you're asking for, and we already have that wording.

I continue to fail to see a defect here.

**Comment by frederick-vs-ja** [comment]
> Note that an implementation might honor `no_unique_address` in some situations and not in others. See intro.object p8: "Otherwise, the circumstances under which the object has zero size are implementation-defined." This is more or less what you're asking for, and we already have that wording.

Yes. But I think the main problem is that the functionality of `no_unique_address` is not merely changing layout of classes.

In order to achieve the fact that "an implementation could choose to not implement the functionality of `[[no_unique_address]]` and still be conforming", we should make "whether a member subobject is potentially-overlapping" and "whether the implementation honor `no_unique_address` for this member (maybe sometimes)" give the same answer.

In some cases, e.g. the member subobject has no padding bytes or the implementation ignores it, `no_unique_address` doesn't affect the layout of the containing class, but the potentially-overlapping property is still added according to the current wording. As core UB is required to be diagnosed in constant evaluation, it is sometimes mandated to detect the aftermath of reusing a potentially-overlapping subobject - it end the lifetime of the containing object.

I think we should relax the restrictions on implementations in a consistent way: if `no_unique_address` is ignored for a member, then no mandated detection of ending lifetime by reusing a potentially-overlapping subobject is caused.

**Comment by jensmaurer** [comment]
I'm still not seeing a core issue.

The intent that an attribute can be ignored syntactically certainly doesn't apply to `no_unique_address`, because follow-on normative definitions such as "transparently replaceable" depend on its syntactic presence, and (as you correctly observe), this might cause constexpr-visible undefined behavior that an implementation is required to detect.
I'm not seeing a problem with the normative wording in that area, since the normative words don't actually mention anything about the possibility to ignore `no_unique_address`.

However, `no_unique_address` strictly reduces the guarantees the standard gives, even if its effects (if any, on a specific implementation) are observable if you look closely enough (e.g. its presence might change the `sizeof` result for an enclosing object).

Can you make a case based on the actual normative words present in the standard, instead of relying on non-normative ideas such as "ignorability"?

**Comment by zygoloid** [comment]
I think the constant evaluation example indicates a problem somewhere. I don't think there was ever any intent when we allowed `construct_at` in constant evaluation that a constant evaluator would need to implement the transparent replacement rules. Another example of that:

```
struct A {
   int x, y;
};
struct B {
  float a;
  int b;
};
union C {
  A a;
  B b;
};
constexpr int f() {
  C c = {};
  std::construct_at(&c.b.b, 5);
  // Does this return 5 if c.a.y and c.b.b are laid out at the same address?
  return c.a.y;
}
```

Rather -- at least during constant evaluation -- I think that `construct_at` should require `location` to point to an object O, and should construct a new object replacing O.

That change wouldn't address the issue that an implementation that completely ignores the `[[no_unique_address]]` attribute is observably non-conforming because it allows constant evaluation to succeed in a case where a correct implementation would fail evaluation because `construct_at` is used to overwrite a potentially-overlapping subobject. I'm not sure whether anything should be done about that, nor whether that's a CWG issue, an EWG issue, or a library issue. It's probably feasible to support transparent replacement of even a potentially-overlapping subobject during constant evaluation.

FWIW, all major implementations permit such transparent replacement during constant evaluation, but we have implementation divergence in the consequences:

```
#include <memory>

struct A {
    virtual constexpr char f() { return 'A'; }
};
struct B : A {
    constexpr char f() override { return 'B'; }
};

constexpr char f() {
    B b;
    A *p = &b;
    std::construct_at(p);
    return p->f();
}

static_assert(f() == 'A'); // GCC result: the object is an A now.
static_assert(f() == 'B'); // Clang, MSVC, ICC result: the object is still a B.
```

**Comment by zygoloid** [comment]
If we change the example to use `b` again after the `construct_at` call:
```diff
     A *p = &b;
     std::construct_at(p);
-    return p->f();
+    return b.f();
 }
```
... then all compilers still accept (none of them think the lifetime of `b` ended), and all of them now return `'B'`.

**Comment by opensdh** [comment]
It sounds a bit meta, but isn't it what we want to say that it's unspecified whether something marked with `[[no_unique_address]]` is potentially overlapping?  Then an implementation that ignores the attribute entirely is conforming, and (to the original point of the issue submission) a program that is correct regardless of the choice of interpretation is by definition correct if we instead restrict to the interpretation where the attribute has no meaning at all.

**Comment by jensmaurer** [comment]
CWG2545

**Comment by frederick-vs-ja** [comment]
CWG2866 address the remain concerns.
