### ISSUE TITLE
[lex.charset] The character sets of ordinary and wide literals are not specified

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#97]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[lex.charset] p6 only says the encodings for these literal are implementation-defined  
> The ordinary and wide literal **encodings** are otherwise implementation-defined.

However, what the character set for these literal is underspecified. Unlike the UTF-8, UTF-16, or UTF-32 literal, which says
> For a UTF-8, UTF-16, or UTF-32 literal, the **UCS scalar value** corresponding to each character of the translation character set is encoded as specified in ISO/IEC 10646 for the respective UCS encoding form.

This implies that the character set for these literals is Unicode character set. 

GCC has a command option `-fexec-charset`, the [document](https://gcc.gnu.org/onlinedocs/gcc-4.1.2/cpp/Character-sets.html) says it can influence the value of the ordinary character literal. Furthermore, as pointed in this [answers](https://stackoverflow.com/a/66326796/11796722), we seem to conflated the concept of "character set" with "encoding" 

For example, the Chinese character `一`, is identified in the Unicode character set, whose scalar value is `4E00`. In the gb2312 character set, its value is `D2BB`. However, it is not defined in the ASCII character set. Encoding just specifies how these values are sorted in memory.

### Suggested resolution

Shall we say the encodings and character sets of the ordinary literal and wide literal are specified by the execution character set? [library.character.seq.general] 1.2 says
> The execution character set and the execution wide-character set are supersets of the basic literal character set ([lex.charset]). The **encodings of the execution character sets** and the sets of additional elements (if any) are **locale-specific**.

**Comment by xmh0511** [comment]
Partial relevant with [p1854r3](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1854r3.pdf).

**Comment by tahonermann** [comment]
No, the character set and encoding of ordinary and wide character and string literals (core language elements) are distinct from the execution (wide-)character set (library elements). This is necessary because for implementations like gcc, the character set and encoding of character and string literals is chosen at compile-time (e.g., via the `-fexec-charset` option) while the character set and encoding of (multibyte) strings that the library operates on is determined by locale settings (and `set_locale`) at run-time.

The terminology issues concerning "character set" and "character encoding" are long standing and require a paper to address.

I don't see an issue to be addressed here.

**Comment by xmh0511** [comment]
In P1854, "ordinary literal encoding" is changed to "encoding of execution character set" while "wide literal encoding" is changed to "encoding of execution wide-character set". Moreover, GCC compiler option "-fexec-charset" is an abbreviation for "execution character set", as specified in GCC's document. For the abbreviation, this might be misleading. Anyway, this part is not clear in the standard.

**Comment by jensmaurer** [comment]
Since the character set follows from the encoding (e.g. UTF-8 is an encoding of Unicode), and the C++ standard is only interested in the encoding (the sequence of bytes coming out of a string literal, or the sequence of bytes that certain library functions operate on), it doesn't seem important to define the character set on its own.

We agree that gcc's `-fexec-charset` is (nowadays) misnamed, but that's not the fault of the standard. And note that talks about "execution character set / encoding" are now limited to the library section, whereas the core section talks about literal encoding only, which is the only thing that matters for the core language.

I'm not seeing a defect here.

**Comment by tahonermann** [comment]
> In P1854, "ordinary literal encoding" is changed to "encoding of execution character set" while "wide literal encoding" is changed to "encoding of execution wide-character set".

This was corrected by a later paper. See the current wording [here](http://eel.is/c++draft/lex.ccon#tab:lex.ccon.literal) and [here](http://eel.is/c++draft/lex.string#tab:lex.string.literal).

> Moreover, GCC compiler option "-fexec-charset" is an abbreviation for "execution character set", as specified in GCC's document.

Historically, the C and C++ standards both used "execution character set" to refer to the encoding of both character and string literals and the locale sensitive encoding associated with C library functions such as `mbstowcs` (indirectly via "extended character set" and "multibyte character"). The C++ standard has clarified that, per existing practice, there is not a requirement that the literal encoding be compatible with the run-time encoding. That is not to say that there isn't a fine mess waiting to be cleaned up, but that will require a significant paper that addresses both WG14 and WG21 concerns.
